[advisories]
version = 2
yanked = "deny"
ignore = [
    # Crate `paste` is no longer maintained
    "RUSTSEC-2024-0436",
    "image@0.25.7",
]

[licenses]
version = 2
allow = [
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "IJG",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Unicode-DFS-2016",
]

exceptions = [
    { allow = [
        "GPL-3.0-or-later",
    ], crate = "jpegxl-rs" },
    { allow = [
        "GPL-3.0-or-later",
    ], crate = "jpegxl-sys" },
    { allow = [
        "LGPL-3.0-or-later",
    ], crate = "libopenraw" },

]
