[library]
version = "2.0.1"
description = "Sandboxed and extendable image loading"
authors = "Sophie Herold"
license = "MPL-2.0 OR LGPL-2.1-or-later"
browse_url = "https://gitlab.gnome.org/GNOME/glycin/"
repository_url = "https://gitlab.gnome.org/GNOME/glycin.git"
website_url = "https://gnome.pages.gitlab.gnome.org/glycin"
docs_url = "https://gnome.pages.gitlab.gnome.org/glycin/libglycin/"
devhelp = true
search_index = true

[theme]
show_index_summary = true

[dependencies."Glib-2.0"]
name = "GLib"
description = "The base utility library"
docs_url = "https://docs.gtk.org/glib/"

[dependencies."GObject-2.0"]
name = "GObject"
description = "The base type system library"
docs_url = "https://docs.gtk.org/gobject/"

[dependencies."Gio-2.0"]
name = "Gio"
description = "GObject Interfaces and Objects, Networking, IPC, and I/O"
docs_url = "https://docs.gtk.org/gio/"

[related."GlyGtk4-2"]
name = "GlyGtk4"
description = "Convert glycin frames to GDK Textures"
docs_url = "https://gnome.pages.gitlab.gnome.org/glycin/libglycin-gtk4/"

[source-location]
base_url = "https://gitlab.gnome.org/GNOME/glycin/-/blob/main/libglycin/include/"

[extra]
urlmap_file = "urlmap.js"
