
# cargo-vet config file

[cargo-vet]
version = "0.9"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.gnome]
url = "https://gitlab.gnome.org/sophie-h/rust-supply-chain/-/raw/main/gnome-created/supply-chain/audits.toml"

[imports.gnome-audited]
url = "https://gitlab.gnome.org/sophie-h/rust-supply-chain/-/raw/main/gnome-audited/audits.toml"

[imports.gnome-created]
url = "https://gitlab.gnome.org/sophie-h/rust-supply-chain/-/raw/main/gnome-created/supply-chain/audits.toml"

[imports.gnome-trusted]
url = "https://gitlab.gnome.org/sophie-h/rust-supply-chain/-/raw/main/gnome-trusted/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.glycin]
audit-as-crates-io = true

[policy.glycin-common]
audit-as-crates-io = true

[policy.glycin-utils]
audit-as-crates-io = true

[[exemptions.byteorder-lite]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.clang-sys]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-deque]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.darling]]
version = "0.20.9"
criteria = "safe-to-deploy"

[[exemptions.darling_core]]
version = "0.20.9"
criteria = "safe-to-deploy"

[[exemptions.darling_macro]]
version = "0.20.9"
criteria = "safe-to-deploy"

[[exemptions.derive_builder]]
version = "0.20.0"
criteria = "safe-to-deploy"

[[exemptions.derive_builder_core]]
version = "0.20.0"
criteria = "safe-to-deploy"

[[exemptions.derive_builder_macro]]
version = "0.20.0"
criteria = "safe-to-deploy"

[[exemptions.dlib]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.dunce]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.enumflags2]]
version = "0.7.10"
criteria = "safe-to-deploy"

[[exemptions.enumflags2_derive]]
version = "0.7.10"
criteria = "safe-to-deploy"

[[exemptions.exr]]
version = "1.72.0"
criteria = "safe-to-deploy"

[[exemptions.flume]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.four-cc]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.futures-timer]]
version = "3.0.3"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.6"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.gif]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.half]]
version = "2.4.1"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.image]]
version = "0.25.2"
criteria = "safe-to-deploy"

[[exemptions.image-webp]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.jpeg-decoder]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.jpegxl-rs]]
version = "0.11.2+libjxl-0.11.1"
criteria = "safe-to-deploy"

[[exemptions.jpegxl-sys]]
version = "0.11.2+libjxl-0.11.1"
criteria = "safe-to-deploy"

[[exemptions.kamadak-exif]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.lazycell]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.lcms2]]
version = "6.1.0"
criteria = "safe-to-deploy"

[[exemptions.lcms2-sys]]
version = "4.0.5"
criteria = "safe-to-deploy"

[[exemptions.lebe]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.libheif-rs]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.libheif-sys]]
version = "2.1.1+1.17.4"
criteria = "safe-to-deploy"

[[exemptions.libloading]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.librsvg-rebind]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.librsvg-rebind-sys]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.libseccomp]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.libseccomp-sys]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.memmap2]]
version = "0.5.4"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.mutate_once]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.nix]]
version = "0.29.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.12.0"
criteria = "safe-to-deploy"

[[exemptions.ordered-stream]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.18"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-crate]]
version = "3.1.0"
criteria = "safe-to-deploy"

[[exemptions.qoi]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.quick-error]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rmp]]
version = "0.8.14"
criteria = "safe-to-deploy"

[[exemptions.rmp-serde]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.safe-transmute]]
version = "0.11.3"
criteria = "safe-to-deploy"

[[exemptions.shlex]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.system-deps]]
version = "7.0.1"
criteria = "safe-to-deploy"

[[exemptions.tiff]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.weezl]]
version = "0.1.8"
criteria = "safe-to-deploy"

[[exemptions.which]]
version = "4.3.0"
criteria = "safe-to-deploy"

[[exemptions.yeslogic-fontconfig-sys]]
version = "6.0.0"
criteria = "safe-to-deploy"

[[exemptions.zune-core]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.zune-inflate]]
version = "0.2.54"
criteria = "safe-to-deploy"

[[exemptions.zune-jpeg]]
version = "0.4.13"
criteria = "safe-to-deploy"
